queue_rules:
  - name: default
    conditions:
      - check-success=continuous-integration/travis-ci/pr

pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
    actions:
      queue:
        method: merge
        name: default
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
